print("Testing from jenkins")
print("Testing poll scm")
print("Testing Jenkins Pipeline scm trigger")
print("Testing Jenkins file execution......")
print("Testing again...")
print("Testing again 2...")
