print("Testing from jenkins")
print("Testing poll scm")
print("Testing Jenkins Pipeline scm trigger")
print("Testing Jenkins file execution......")
print("Testing again...")
print("Testing again 2...")
print("Works without checkout in stage")
print("Removed scm schedule and checking the trigger without that")
